import {useEffect,useMemo,useState,type ReactNode} from "react";
import {AppWindow,CalendarDays,ChevronLeft,ChevronRight,Clock,FileCheck2,FileClock,FileCog,Flame,FolderInput,Globe2,Mail,Smartphone,StickyNote,Usb} from "lucide-react";
import {readDailyActivities,watchDailyActivity,type DailyActivity} from "../dailyActivity";
interface CalendarItem{title?:string;start?:string;end?:string;location?:string;}
interface Note{id:string;title?:string;text:string;color?:string;reminderAt?:string;}
const metadata:Record<string,{label:string;color:string;icon:ReactNode}>={gmail:{label:"Gmail",color:"#d84b40",icon:<Mail/>},outlook:{label:"Outlook",color:"#2476d3",icon:<Mail/>},recent:{label:"Recent files",color:"#607d99",icon:<FileClock/>},phone:{label:"Phone",color:"#5b54c7",icon:<Smartphone/>},domain:{label:"Domain",color:"#168a86",icon:<Globe2/>},usb:{label:"USB drives",color:"#697685",icon:<Usb/>},fire:{label:"Fire Mountain",color:"#e05c2f",icon:<Flame/>},studio:{label:"File Studio",color:"#9a5bb8",icon:<FileCog/>},folders:{label:"Folder transfers",color:"#269562",icon:<FolderInput/>},applications:{label:"Applications",color:"#3c72a8",icon:<AppWindow/>}};
const dayKey=(date:Date)=>date.toLocaleDateString("sv-SE");
export default function DailyJob({storageScope}:{storageScope:string}){
 const [date,setDate]=useState(()=>new Date()),[activities,setActivities]=useState<DailyActivity[]>(()=>readDailyActivities(storageScope));
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)setActivities(readDailyActivities(storageScope,date));});return()=>{active=false;};},[date,storageScope]);
 useEffect(()=>watchDailyActivity(()=>window.setTimeout(()=>setActivities(readDailyActivities(storageScope,date)),0)),[date,storageScope]);
 const calendar=useMemo(()=>{try{const blocks=JSON.parse(localStorage.getItem(`folderrocket-daily-calendars-${storageScope}`)||"{}");return (Object.values(blocks).flat() as CalendarItem[]).filter(item=>item.start&&dayKey(new Date(item.start))===dayKey(date)).sort((a,b)=>String(a.start).localeCompare(String(b.start)));}catch{return[];}},[date,storageScope]);
 const notes=useMemo(()=>{try{const values=JSON.parse(localStorage.getItem(`folderrocket-sticky-notes-${storageScope}`)||"[]") as Note[];const tomorrow=new Date(date);tomorrow.setDate(tomorrow.getDate()+1);return values.filter(note=>note.reminderAt&&[dayKey(date),dayKey(tomorrow)].includes(dayKey(new Date(note.reminderAt)))).sort((a,b)=>String(a.reminderAt).localeCompare(String(b.reminderAt)));}catch{return[];}},[date,storageScope]);
 const groups=Object.entries(activities.reduce<Record<string,DailyActivity[]>>((result,item)=>{(result[item.kind]??=[]).push(item);return result;},{}));
 const shift=(days:number)=>setDate(current=>{const next=new Date(current);next.setDate(next.getDate()+days);return next;});
 return <main className="dailyJobPage"><header><div><h1>Daily Job</h1><p>Priorities and work recorded for the selected day.</p></div><nav><button onClick={()=>shift(-1)} title="Previous day"><ChevronLeft size={16}/></button><input type="date" value={dayKey(date)} onChange={event=>{const next=new Date(`${event.target.value}T12:00:00`);if(!Number.isNaN(next.getTime()))setDate(next);}}/><button onClick={()=>shift(1)} title="Next day"><ChevronRight size={16}/></button><button onClick={()=>setDate(new Date())}>Today</button></nav></header>
 <section className="dailyPriorities"><h2><CalendarDays size={18}/>Priorities</h2><div className="dailyEventRows">{calendar.map((item,index)=><article className="dailyEventRow calendar" key={`${item.start}-${index}`}><span className="dailyEventLogo"><CalendarDays/></span><strong>{item.title||"Calendar appointment"}</strong><time>{new Date(item.start!).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time><small>{item.end?`Until ${new Date(item.end).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`:""}</small><small>{item.location||"Google Calendar"}</small></article>)}{notes.map(note=><article className={`dailyEventRow note note-${note.color||"yellow"}`} key={note.id}><span className="dailyEventLogo"><StickyNote/></span><strong>{note.title||note.text||"Post-it reminder"}</strong><time>{new Date(note.reminderAt!).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time><small>{dayKey(new Date(note.reminderAt!))===dayKey(date)?"Today":"Tomorrow"}</small><small>Post-it</small></article>)}{!calendar.length&&!notes.length&&<p>No Calendar appointments or post-it reminders for this day or the next.</p>}</div></section>
 <section className="dailySummary"><h2><FileCheck2 size={18}/>Today’s work</h2><p>{activities.length?`${activities.length} important action${activities.length===1?"":"s"} recorded across ${groups.length} block${groups.length===1?"":"s"}.`:"No work activity has been recorded for this day yet."}</p></section>
 <div className="dailyGroups">{groups.map(([kind,items])=>{const meta=metadata[kind]||{label:kind,color:"#607d99",icon:<Clock/>};return <section key={kind} style={{"--daily-accent":meta.color} as React.CSSProperties}><h3><span className="dailyGroupLogo">{meta.icon}</span>{meta.label}<small>{items.length}</small></h3>{items.map(item=><article className="dailyActivityRow" key={item.id}><time>{new Date(item.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time><strong>{item.summary}</strong><small>{item.files?.join(" · ")||"—"}</small><small title={item.destination}>{item.destination||"—"}</small></article>)}</section>;})}</div>
 </main>;
}
