import {useEffect,useMemo,useState,type ReactNode} from "react";
import {AppWindow,Flag,CalendarDays,ChevronLeft,ChevronRight,Clock,FileCheck2,FileClock,FileCog,Flame,FolderInput,Globe2,Mail,Smartphone,StickyNote,Usb} from "lucide-react";
import {readDailyActivities,removeDailyActivity,watchDailyActivity,type DailyActivity} from "../dailyActivity";
import {API_BASE_URL} from "../api";
interface CalendarItem{title?:string;start?:string;end?:string;location?:string;}
interface Note{id:string;title?:string;text:string;color?:string;reminderAt?:string;}
const metadata:Record<string,{label:string;color:string;icon:ReactNode}>={gmail:{label:"Gmail",color:"#d84b40",icon:<Mail/>},outlook:{label:"Outlook",color:"#2476d3",icon:<Mail/>},recent:{label:"Recent files",color:"#607d99",icon:<FileClock/>},phone:{label:"Phone",color:"#5b54c7",icon:<Smartphone/>},domain:{label:"Domain",color:"#168a86",icon:<Globe2/>},usb:{label:"USB drives",color:"#697685",icon:<Usb/>},fire:{label:"Fire Mountain",color:"#e05c2f",icon:<Flame/>},studio:{label:"File Studio",color:"#9a5bb8",icon:<FileCog/>},folders:{label:"Folder transfers",color:"#269562",icon:<FolderInput/>},applications:{label:"Applications",color:"#3c72a8",icon:<AppWindow/>}};
const dayKey=(date:Date)=>date.toLocaleDateString("sv-SE");
const formatDailyDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?"—":`${date.toLocaleDateString("it-IT",{day:"2-digit",month:"2-digit",year:"numeric"}).replaceAll("/"," ")} ${date.toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"})}`;};
export default function DailyJob({storageScope,onOpenWorkspace}:{storageScope:string;onOpenWorkspace:(kind:DailyActivity["kind"])=>void}){
 const [date,setDate]=useState(()=>new Date()),[activities,setActivities]=useState<DailyActivity[]>(()=>readDailyActivities(storageScope));
 const [undoing,setUndoing]=useState<string|null>(null);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)setActivities(readDailyActivities(storageScope,date));});return()=>{active=false;};},[date,storageScope]);
 useEffect(()=>watchDailyActivity(()=>window.setTimeout(()=>setActivities(readDailyActivities(storageScope,date)),0)),[date,storageScope]);
 const calendar=useMemo(()=>{try{const blocks=JSON.parse(localStorage.getItem(`folderrocket-daily-calendars-${storageScope}`)||"{}");return (Object.values(blocks).flat() as CalendarItem[]).filter(item=>item.start&&dayKey(new Date(item.start))===dayKey(date)).sort((a,b)=>String(a.start).localeCompare(String(b.start)));}catch{return[];}},[date,storageScope]);
 const notes=useMemo(()=>{try{const values=JSON.parse(localStorage.getItem(`folderrocket-sticky-notes-${storageScope}`)||"[]") as Note[];const tomorrow=new Date(date);tomorrow.setDate(tomorrow.getDate()+1);return values.filter(note=>note.reminderAt&&[dayKey(date),dayKey(tomorrow)].includes(dayKey(new Date(note.reminderAt)))).sort((a,b)=>String(a.reminderAt).localeCompare(String(b.reminderAt)));}catch{return[];}},[date,storageScope]);
 const groups=Object.entries(activities.reduce<Record<string,DailyActivity[]>>((result,item)=>{(result[item.kind]??=[]).push(item);return result;},{}));
 const shift=(days:number)=>setDate(current=>{const next=new Date(current);next.setDate(next.getDate()+days);return next;});
 async function undoActivity(item:DailyActivity){
  if(!item.undo||undoing)return;
  if(!window.confirm(`Undo “${item.summary}”? FolderRocket will reverse the recorded file operation.`))return;
  setUndoing(item.id);
  try{const response=await fetch(`${API_BASE_URL}/daily-job/undo`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({undo:item.undo})});const data=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(data.message||"Unable to undo this operation.");setActivities(removeDailyActivity(storageScope,item.id,date));}
  catch(error){window.alert(error instanceof Error?error.message:"Unable to undo this operation.");}
  finally{setUndoing(null);}
 }
 function removeLog(item:DailyActivity){if(window.confirm("Remove this entry from Daily Job history?"))setActivities(removeDailyActivity(storageScope,item.id,date));}
 return <main className="dailyJobPage"><header><div><h1>Daily Job</h1><p>Priorities and work recorded for the selected day.</p></div><nav><button onClick={()=>shift(-1)} title="Previous day"><ChevronLeft size={16}/></button><input type="date" value={dayKey(date)} onChange={event=>{const next=new Date(`${event.target.value}T12:00:00`);if(!Number.isNaN(next.getTime()))setDate(next);}}/><button onClick={()=>shift(1)} title="Next day"><ChevronRight size={16}/></button><button onClick={()=>setDate(new Date())}>Today</button></nav></header>
 <section className="dailyPriorities"><h2 className="dailySectionTitle"><span className="dailySectionLogo priorities"><Flag size={25}/></span>Priorities</h2>{calendar.length>0&&<div className="dailyPriorityCategory"><h3><CalendarDays size={15}/>Calendar</h3><div className="dailyEventRows">{calendar.map((item,index)=><article className="dailyEventRow calendar" key={`${item.start}-${index}`}><span className="dailyEventLogo"><CalendarDays/></span><strong>{item.title||"Calendar appointment"}</strong><time>{formatDailyDate(item.start||"")}</time><small>{item.end?`Until ${new Date(item.end).toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"})}`:""}</small><small>{item.location||"Google Calendar"}</small></article>)}</div></div>}{notes.length>0&&<div className="dailyPriorityCategory"><h3><StickyNote size={15}/>Post-it reminders</h3><div className="dailyEventRows">{notes.map(note=><article className={`dailyEventRow note note-${note.color||"yellow"}`} key={note.id}><span className="dailyEventLogo"><StickyNote/></span><strong>{note.title||note.text||"Post-it reminder"}</strong><time>{formatDailyDate(note.reminderAt||"")}</time><small>{dayKey(new Date(note.reminderAt!))===dayKey(date)?"Today":"Tomorrow"}</small><small>Post-it</small></article>)}</div></div>}{!calendar.length&&!notes.length&&<p>No Calendar appointments or post-it reminders for this day or the next.</p>}</section>
 <section className="dailySummary"><h2 className="dailySectionTitle"><span className="dailySectionLogo work"><FileCheck2 size={25}/></span>Today’s work</h2><p>{activities.length?`${activities.length} important action${activities.length===1?"":"s"} recorded across ${groups.length} block${groups.length===1?"":"s"}.`:"No work activity has been recorded for this day yet."}</p><div className="dailyGroups">{groups.map(([kind,items])=>{const meta=metadata[kind]||{label:kind,color:"#607d99",icon:<Clock/>};return <section key={kind} style={{"--daily-accent":meta.color} as React.CSSProperties}><h3><span className="dailyGroupLogo">{meta.icon}</span>{meta.label}<small>{items.length}</small></h3>{items.map(item=><article className="dailyActivityRow" key={item.id}><time>{formatDailyDate(item.at)}</time><strong title={item.summary}>{item.summary}</strong><small className="dailyActivityDetails" title={`${meta.label} · ${item.destination||"—"} · ${item.files?.join(" · ")||"No files"}`}>From: {meta.label} · To: {item.destination||"—"} · {item.files?.join(" · ")||"No files"}</small><div className="dailyActivityActions"><button type="button" onClick={()=>onOpenWorkspace(item.kind)}>Open</button>{item.undo?<button type="button" className="dailyUndoLog" disabled={undoing===item.id} onClick={()=>void undoActivity(item)}>{undoing===item.id?"Undoing…":"Undo"}</button>:<button type="button" className="dailyUndoLog" onClick={()=>removeLog(item)}>Remove log</button>}</div></article>)}</section>;})}</div></section>
 </main>;
}
