import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from "react";
import {CalendarDays,ChevronRight,Clock,StickyNote} from "lucide-react";
interface AgendaItem{id:string;title:string;at:string;kind:"calendar"|"note";color?:string;}
const dayKey=(date:Date)=>date.toLocaleDateString("sv-SE");
function readAgenda(scope:string){const now=new Date(),tomorrow=new Date(now);tomorrow.setDate(tomorrow.getDate()+1);const days=[dayKey(now),dayKey(tomorrow)],items:AgendaItem[]=[];try{const blocks=JSON.parse(localStorage.getItem(`folderrocket-daily-calendars-${scope}`)||"{}");for(const event of Object.values(blocks).flat() as Array<{title?:string;start?:string}>){if(event.start&&days.includes(dayKey(new Date(event.start))))items.push({id:`calendar-${event.start}-${event.title}`,title:event.title||"Calendar appointment",at:event.start,kind:"calendar"});}}catch{/* malformed cache */}try{const notes=JSON.parse(localStorage.getItem(`folderrocket-sticky-notes-${scope}`)||"[]") as Array<{id:string;title?:string;text?:string;reminderAt?:string;color?:string}>;for(const note of notes){if(note.reminderAt&&days.includes(dayKey(new Date(note.reminderAt))))items.push({id:note.id,title:note.title||note.text||"Post-it reminder",at:note.reminderAt,kind:"note",color:note.color});}}catch{/* malformed notes */}return items.sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime()).slice(0,12);}
export default function DailyAgendaRail({storageScope,onOpenDailyJob}:{storageScope:string;onOpenDailyJob:()=>void}){
 const positionKey=`folderrocket-agenda-position-${storageScope}`,railRef=useRef<HTMLElement>(null),[items,setItems]=useState(()=>readAgenda(storageScope));
 const [position,setPosition]=useState<{side:"left"|"right";top:number}>(()=>{try{const saved=JSON.parse(localStorage.getItem(positionKey)||"null");if(saved&&["left","right"].includes(saved.side)&&Number.isFinite(saved.top))return saved;}catch{/* default */}return {side:"left",top:Math.max(100,window.innerHeight/2-110)};});
 useEffect(()=>{localStorage.setItem(positionKey,JSON.stringify(position));},[position,positionKey]);
 useEffect(()=>{const refresh=()=>setItems(readAgenda(storageScope));window.addEventListener("storage",refresh);window.addEventListener("folderrocket-calendar-context",refresh);const timer=window.setInterval(refresh,60000);return()=>{window.removeEventListener("storage",refresh);window.removeEventListener("folderrocket-calendar-context",refresh);window.clearInterval(timer);};},[storageScope]);
 function startMove(event:ReactPointerEvent<HTMLDivElement>){event.preventDefault();const bounds=railRef.current?.getBoundingClientRect();if(!bounds)return;const offsetY=event.clientY-bounds.top;const move=(next:PointerEvent)=>setPosition({side:next.clientX<window.innerWidth/2?"left":"right",top:Math.max(8,Math.min(window.innerHeight-150,next.clientY-offsetY))});const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop);}
 return <aside ref={railRef} className={`dailyAgendaRail side-${position.side}`} style={{top:position.top}} aria-label="Today and tomorrow"><div className="dailyAgendaHandle" onPointerDown={startMove} title="Drag to move or switch side"><CalendarDays size={18}/><span>TO DO</span><ChevronRight size={15}/></div><section><header><div><strong>To do</strong><small>Today & tomorrow</small></div><button type="button" onClick={onOpenDailyJob}>Daily Job</button></header><div className="dailyAgendaList">{items.map(item=><article key={item.id} className={`agenda-${item.kind} note-${item.color||""}`}>{item.kind==="calendar"?<CalendarDays size={15}/>:<StickyNote size={15}/>}<div><strong>{item.title}</strong><small><Clock size={11}/>{new Date(item.at).toLocaleString([],{weekday:"short",hour:"2-digit",minute:"2-digit"})}</small></div></article>)}{!items.length&&<p>No appointments or reminders for today and tomorrow.</p>}</div></section></aside>;
}
