import {useCallback, useEffect, useRef, useState, type ChangeEvent} from "react";
import {ArrowLeft, Check, ChevronDown, LoaderCircle, Mail, Paperclip, RefreshCw, Send, Share2, X} from "lucide-react";
import {API_BASE_URL} from "../api";
import type {WorkspaceWorld} from "../worlds";
import type {CSSProperties} from "react";

type ThreadSummary={id:string;threadId:string;blockId:string;subject:string;snippet:string;updatedAt:string;messageCount:number;accountEmail:string;shared:boolean;sourceWorldId?:string;sourceWorldName?:string;available?:boolean};
type ThreadMessage={id:string;threadId:string;messageId:string;inReplyTo:string;references:string;from:string;replyTo?:string;to:string;cc?:string;subject:string;date:string;receivedAt:string;text:string;attachments:Array<{id:string;name:string;mimeType:string;size:number}>};
type ThreadData={id:string;messages:ThreadMessage[];blockId:string;accountEmail:string;shared:boolean;sourceWorldId?:string};
type PickedAttachment={path:string;name:string};

function firstEmailAddress(value:string){return String(value||"").match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]||"";}
function defaultReplyRecipient(messages:ThreadMessage[],accountEmail:string){
    const own=firstEmailAddress(accountEmail).toLocaleLowerCase();
    const incoming=[...messages].reverse().find(message=>firstEmailAddress(message.from).toLocaleLowerCase()!==own);
    if(incoming)return firstEmailAddress(incoming.replyTo||incoming.from);
    const latest=[...messages].reverse().find(message=>message.to);
    return firstEmailAddress(latest?.to||"");
}

export default function EmailConversations({world,worlds,focusThreadId,onBack,onViewGraph,onGoToDashboard}:{world:WorkspaceWorld;worlds:WorkspaceWorld[];focusThreadId?:string;onBack:()=>void;onViewGraph:(threadId?:string)=>void;onGoToDashboard:()=>void}) {
    const [threads,setThreads]=useState<ThreadSummary[]>([]);const [selected,setSelected]=useState<ThreadSummary|null>(null);const [detail,setDetail]=useState<ThreadData|null>(null);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [text,setText]=useState("");const [to,setTo]=useState("");const [attachments,setAttachments]=useState<PickedAttachment[]>([]);const [shareTarget,setShareTarget]=useState<string[]>([]);const [shareOpen,setShareOpen]=useState(false);const [notice,setNotice]=useState("");const [query,setQuery]=useState("");const fileInput=useRef<HTMLInputElement|null>(null);const listGeneration=useRef(0);const threadGeneration=useRef(0);
    const root=`${API_BASE_URL}/worlds/${encodeURIComponent(world.id)}/email/conversations`;
    const loadThreads=useCallback(async()=>{const token=++listGeneration.current;setLoading(true);setError("");try{const response=await fetch(root,{credentials:"include"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Could not load Gmail conversations.");if(token!==listGeneration.current)return;const next=(data.threads||[]) as ThreadSummary[];setThreads(next);setSelected(current=>current&&next.some(item=>item.id===current.id&&item.blockId===current.blockId)?next.find(item=>item.id===current.id&&item.blockId===current.blockId)||current:focusThreadId?next.find(item=>item.threadId===focusThreadId)||next[0]||null:next[0]||null);if(!data.selectedBlockId&&!next.some(item=>item.shared))setNotice("No Gmail account is selected for this planet. Select its account in the Gmail dashboard block.");}catch(reason){if(token===listGeneration.current)setError(reason instanceof Error?reason.message:"Could not load Gmail conversations.");}finally{if(token===listGeneration.current)setLoading(false);}},[root,focusThreadId]);
    useEffect(()=>{const timer=window.setTimeout(()=>void loadThreads(),0);return()=>{window.clearTimeout(timer);listGeneration.current+=1;};},[loadThreads]);
    const currentId=selected?.threadId||"";const currentBlock=selected?.blockId||"";
    const loadThread=useCallback(async()=>{if(!currentId||!currentBlock){setDetail(null);return;}const token=++threadGeneration.current;setLoading(true);setError("");try{const response=await fetch(`${root}/${encodeURIComponent(currentId)}?blockId=${encodeURIComponent(currentBlock)}`,{credentials:"include"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Could not open this conversation.");if(token===threadGeneration.current){setDetail(data as ThreadData);setTo(defaultReplyRecipient(data.messages||[],data.accountEmail||""));}}catch(reason){if(token===threadGeneration.current){setDetail(null);setError(reason instanceof Error?reason.message:"Could not open this conversation.");}}finally{if(token===threadGeneration.current)setLoading(false);}},[root,currentId,currentBlock]);
    useEffect(()=>{const timer=window.setTimeout(()=>void loadThread(),0);return()=>{window.clearTimeout(timer);threadGeneration.current+=1;};},[loadThread]);
    function pickFiles(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);const found:PickedAttachment[]=[];for(const file of files){const path=window.folderRocketDesktop?.getPathForFile(file);if(path)found.push({path,name:file.name});}setAttachments(current=>[...current,...found].slice(0,10));event.target.value="";if(files.length&&!found.length)setError("File attachments are available from the FolderRocket desktop file picker.");}
    async function submit(mode:"draft"|"send"){if(!selected||!detail||!text.trim()||busy)return;if(mode==="send"&&!window.confirm("Send this reply in the current Gmail conversation?"))return;setBusy(true);setError("");setNotice("");try{const last=[...detail.messages].reverse().find(message=>message.messageId);const response=await fetch(`${root}/${encodeURIComponent(selected.threadId)}/reply`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({blockId:selected.blockId,to,subject:last?.subject||selected.subject,text,attachments,originalMessageId:last?.messageId||"",references:last?.references||"",mode})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Could not save this reply.");setNotice(mode==="send"?"Reply sent in the Gmail conversation.":"Reply saved to Gmail drafts.");setText("");setAttachments([]);if(mode==="send")await loadThread();}catch(reason){setError(reason instanceof Error?reason.message:"Could not send this reply.");}finally{setBusy(false);}}
    async function share(){if(!selected||!shareTarget.length)return;setBusy(true);setError("");try{const response=await fetch(`${root}/${encodeURIComponent(selected.threadId)}/share`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({blockId:selected.blockId,targetWorldIds:shareTarget})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Could not share this conversation.");setShareOpen(false);setShareTarget([]);setNotice("Conversation reference shared. The destination planet was not connected to this Gmail account.");}catch(reason){setError(reason instanceof Error?reason.message:"Could not share this conversation.");}finally{setBusy(false);}}
    async function removeShared(){if(!selected?.shared)return;setBusy(true);try{const response=await fetch(`${root}/${encodeURIComponent(selected.threadId)}/share?blockId=${encodeURIComponent(selected.blockId)}`,{method:"DELETE",credentials:"include"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Could not remove this shared reference.");setThreads(current=>current.filter(item=>item!==selected));setSelected(null);setNotice("Shared reference removed from this planet only.");}catch(reason){setError(reason instanceof Error?reason.message:"Could not remove this shared reference.");}finally{setBusy(false);}}
    const filtered=threads.filter(thread=>!query.trim()||`${thread.subject} ${thread.snippet} ${thread.accountEmail}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
    return <main className="emailConversationsPage"><header className="emailConversationsHeader"><button type="button" onClick={onBack} aria-label="Back to workspace"><ArrowLeft size={16}/></button><div className="emailConversationsTitle"><Mail size={22}/><span><strong>Email Conversations</strong><small>{world.name} · Gmail</small></span></div><button type="button" className="emailGraphButton" onClick={()=>onViewGraph(selected?.threadId)}><Share2 size={15}/>Planet graph</button><button type="button" onClick={()=>void loadThreads()} disabled={loading} aria-label="Refresh conversations"><RefreshCw size={15} className={loading?"planetGraphSpin":""}/></button></header>
        {error&&<p className="emailConversationError" role="alert">{error}</p>}{notice&&<p className="emailConversationNotice" role="status"><Check size={14}/>{notice}<button type="button" onClick={()=>setNotice("")} aria-label="Dismiss">×</button></p>}
        <div className="emailConversationLayout"><aside className="emailConversationList"><label className="emailConversationSearch"><Mail size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search conversations"/></label><div className="emailConversationRows">{loading&&!threads.length?<p className="emailConversationEmpty"><LoaderCircle className="planetGraphSpin"/>Loading conversations…</p>:filtered.map(thread=><button type="button" key={`${thread.blockId}:${thread.id}`} className={`emailConversationRow${selected?.id===thread.id&&selected?.blockId===thread.blockId?" active":""}`} onClick={()=>{setSelected(thread);setText("");setAttachments([]);}}><span className="emailConversationRowTop"><strong>{thread.subject||"(no subject)"}</strong><time>{thread.updatedAt?new Date(thread.updatedAt).toLocaleDateString():""}</time></span><small>{thread.accountEmail||"Gmail"}{thread.shared?` · Shared from ${thread.sourceWorldName||thread.sourceWorldId}`:""}</small><span>{thread.snippet||"Shared conversation reference"}</span></button>)}{!filtered.length&&!loading&&<p className="emailConversationEmpty">No conversations found.</p>}</div><small className="emailConversationAccount">Selected Gmail for {world.name}: {threads.find(item=>!item.shared)?.accountEmail||"not selected"}</small></aside>
            <section className="emailConversationThread">{!selected?<div className="emailConversationEmptyState"><Mail size={35}/><h2>No Gmail conversation selected</h2><p>Choose this planet’s Gmail account in its dashboard block, or select a conversation shared here.</p><button type="button" onClick={onGoToDashboard}>Open dashboard</button></div>:<><div className="emailThreadHeading"><div><h2>{selected.subject||"(no subject)"}</h2><p>{selected.accountEmail||"Gmail conversation"}{selected.shared&&` · Shared from ${selected.sourceWorldName||selected.sourceWorldId}`}</p></div><button type="button" onClick={()=>{setShareTarget([]);setShareOpen(true);}} disabled={selected.shared}><Share2 size={14}/>Share</button>{selected.shared&&<button type="button" onClick={()=>void removeShared()} disabled={busy}><X size={14}/>Remove from planet</button>}</div>
                {!selected.available&&selected.shared&&<p className="emailConversationError">The source Gmail connection is unavailable. Reconnect it in the source planet to open this thread.</p>}
                <div className="emailMessageList">{detail?.messages.map(message=><article className="emailMessageCard" key={message.id}><header><strong>{message.from||"Unknown sender"}</strong><time>{message.receivedAt?new Date(message.receivedAt).toLocaleString():message.date}</time></header><small>To: {message.to||"—"}{message.cc?` · Cc: ${message.cc}`:""}</small><pre>{message.text||"(No readable message text)"}</pre>{message.attachments?.length>0&&<div className="emailMessageAttachments">{message.attachments.map(file=><span key={file.id}><Paperclip size={13}/>{file.name}</span>)}</div>}</article>)||<p className="emailConversationEmpty">{loading?<><LoaderCircle className="planetGraphSpin"/> Loading message…</>:"Select this thread to load messages."}</p>}</div>
                <section className="emailReplyComposer"><div className="emailReplyTitle"><strong>Reply in this conversation</strong><small>{to?`To ${to}`:"Recipient will be taken from the conversation"}</small></div><label className="emailReplyRecipient">To<input type="email" value={to} onChange={event=>setTo(event.target.value)} placeholder="recipient@example.com"/></label><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Write your reply…" maxLength={12000}/><input ref={fileInput} type="file" multiple hidden onChange={pickFiles}/>{attachments.length>0&&<div className="emailReplyFiles">{attachments.map((item,index)=><span key={`${item.path}:${index}`}>{item.name}<button type="button" onClick={()=>setAttachments(current=>current.filter((_,at)=>at!==index))} aria-label={`Remove ${item.name}`}>×</button></span>)}</div>}<footer><button type="button" onClick={()=>fileInput.current?.click()} disabled={busy}><Paperclip size={14}/>Attach files</button><span/>{selected.available===false&&selected.shared&&<small>Reconnect the source Gmail account before replying.</small>}<button type="button" onClick={()=>void submit("draft")} disabled={busy||!text.trim()||!detail}><ChevronDown size={14}/>Save draft</button><button type="button" className="emailSendReply" onClick={()=>void submit("send")} disabled={busy||!text.trim()||!detail}><Send size={14}/>{busy?<LoaderCircle className="planetGraphSpin" size={14}/>:"Send reply"}</button></footer></section>
            </>}</section></div>
        {shareOpen&&selected&&<div className="emailShareScrim" onMouseDown={event=>{if(event.target===event.currentTarget)setShareOpen(false);}}><section className="emailShareDialog" role="dialog" aria-modal="true" aria-labelledby="emailShareTitle"><header><div><h2 id="emailShareTitle">Share conversation reference</h2><p>Only a reference is shared. This does not connect Gmail or copy messages to another planet.</p></div><button type="button" onClick={()=>setShareOpen(false)} aria-label="Close"><X size={16}/></button></header><div className="emailShareWorlds">{worlds.filter(item=>item.id!==world.id).map(item=><label key={item.id}><input type="checkbox" checked={shareTarget.includes(item.id)} onChange={event=>setShareTarget(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><span className={`worldPlanet ${item.style}`} style={{"--planet-color":item.color} as CSSProperties}><i/><b/><em/></span>{item.name}</label>)}</div><footer><button type="button" onClick={()=>setShareOpen(false)}>Cancel</button><button type="button" onClick={()=>void share()} disabled={!shareTarget.length||busy}>Share reference</button></footer></section></div>}
    </main>;
}
