import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronDown,ChevronRight,Download,ExternalLink,Flame,FolderClosed,RefreshCw,Search,Smartphone} from 'lucide-react';
import {UsbFileIcon} from './UsbSourcePanel';
import {API_BASE_URL} from '../api';
import {recordDailyActivity} from '../dailyActivity';
import {SEARCH_RESULT_TYPE} from './SearchWorkspace';
import {phoneFileType} from '../phoneFiles';
interface Device{id:string;name:string} interface PhoneFile{name:string;size:number;path?:string;extension?:string;mimeType?:string;typeLabel?:string;modifiedAt?:string;segments?:string[]} interface Contents{folders:{name:string}[];files:PhoneFile[]}
interface Props{hours?:number;onHoursChange?:(hours:number)=>void}
export default function PhoneSourcePanel({hours=24,onHoursChange}:Props){
 const[devices,setDevices]=useState<Device[]>([]),[device,setDevice]=useState(''),[tree,setTree]=useState<Record<string,Contents>>({}),[expanded,setExpanded]=useState<string[]>(['[]']);
 const[ready,setReady]=useState<Record<string,PhoneFile>>({}),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[recentBusy,setRecentBusy]=useState(false),[error,setError]=useState(''),[category,setCategory]=useState<'all'|'image'|'file'>('all'),[query,setQuery]=useState('');
 const[recent,setRecent]=useState<PhoneFile[]>([]),[counts,setCounts]=useState({image:0,file:0}),[truncated,setTruncated]=useState(false);const generation=useRef(0),recentRequest=useRef(0);
 async function api(action:string,body?:object){const response=await fetch(`${API_BASE_URL}/devices/phone${action}`,body?{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{credentials:'include'});const data=await response.json();if(!response.ok)throw new Error(data.message||'Phone unavailable.');return data;}
 async function open(id:string,segments:string[]){const token=generation.current,key=JSON.stringify(segments);setBusy(true);setError('');try{const data=await api('/files',{deviceId:id,segments});if(token===generation.current){setTree(current=>({...current,[key]:data}));setExpanded(current=>current.includes(key)?current:[...current,key]);}}catch(reason){if(token===generation.current)setError(String(reason instanceof Error?reason.message:reason));}finally{if(token===generation.current)setBusy(false);}}
 async function scanRecent(id=device){if(!id)return;const token=++recentRequest.current;setRecentBusy(true);setError('');try{const data=await api('/recent',{deviceId:id,segments:[],hours,category});if(token===recentRequest.current){setRecent(data.files||[]);setCounts(data.counts||{image:0,file:0});setTruncated(Boolean(data.truncated));}}catch(reason){if(token===recentRequest.current)setError(String(reason instanceof Error?reason.message:reason));}finally{if(token===recentRequest.current)setRecentBusy(false);}}
 function select(id:string){generation.current++;recentRequest.current++;setDevice(id);setTree({});setReady({});setSelected([]);setRecent([]);setExpanded(['[]']);if(id){const selectedDevice=devices.find(item=>item.id===id);recordDailyActivity({kind:'phone',summary:`Connected phone ${selectedDevice?.name||id}`});void open(id,[]);}}
 async function refresh(){setBusy(true);setError('');try{const data=await api('');const next=data.devices?.some((item:Device)=>item.id===device)?device:data.devices?.[0]?.id||'';setDevices(data.devices||[]);if(next)select(next);else{setDevice('');setRecent([]);setTree({});}}catch(reason){setError(String(reason instanceof Error?reason.message:reason));}finally{setBusy(false);}}
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void refresh();});return()=>{active=false;generation.current++;recentRequest.current++;};},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!device)return;let active=true;queueMicrotask(()=>{if(active)void scanRecent(device);});const timer=window.setInterval(()=>void scanRecent(device),60000);return()=>{active=false;window.clearInterval(timer);};},[device,hours,category]); // eslint-disable-line react-hooks/exhaustive-deps
 async function copy(file:PhoneFile,segments:string[]){const token=generation.current;setBusy(true);setError('');try{const data=await api('/copy',{deviceId:device,segments,name:file.name});if(token===generation.current){setReady(current=>({...current,[JSON.stringify([...segments,file.name])]:data}));recordDailyActivity({kind:'phone',summary:`Imported ${file.name} from phone`,files:[file.name],destination:data.path});}}catch(reason){setError(String(reason instanceof Error?reason.message:reason));}finally{if(token===generation.current)setBusy(false);}}
 const recentVisible=useMemo(()=>recent.filter(file=>`${file.name} ${file.typeLabel||''}`.toLowerCase().includes(query.toLowerCase())),[recent,query]);
 function fileRow(file:PhoneFile,segments:string[],prefix=''){const key=JSON.stringify([...segments,file.name]),local=ready[key],kind=phoneFileType(file);return <div className={selected.includes(key)?'inspectorFile usbInspectorFile selectedAttachment':'inspectorFile usbInspectorFile'} key={`${prefix}${key}`} draggable={Boolean(local)} onClick={()=>{if(local)setSelected(current=>current.includes(key)?current.filter(value=>value!==key):[...current,key]);}} onDragStart={event=>{if(!local)return;const value=JSON.stringify(selected.includes(key)?selected.map(value=>ready[value]).filter(Boolean):[local]);event.dataTransfer.setData('application/x-folderrocket-daily-source','phone');event.dataTransfer.setData(SEARCH_RESULT_TYPE,value);event.dataTransfer.setData('text/plain',`folderrocket-search:${value}`);}}>{local&&<button className="recentFileFire" title="Add to Fire Mountain" onClick={event=>{event.stopPropagation();window.dispatchEvent(new CustomEvent('folderrocket-add-to-fire',{detail:[local]}));}}><Flame size={14}/></button>}<span className="inspectorFileName"><UsbFileIcon name={kind.iconName}/><strong>{file.name}</strong><em className={`phoneFileType ${kind.category}`}>{kind.label}</em></span>{local?<small>Ready</small>:<button title={`Import ${file.name}`} disabled={busy} onClick={()=>void copy(file,segments)}><Download size={14}/></button>}{local&&<button className="recentFileOpen" title="Open file" onClick={event=>{event.stopPropagation();void fetch(`${API_BASE_URL}/search-files/open`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:local.path})});}}><ExternalLink size={14}/></button>}</div>}
 function renderTree(segments:string[]):React.ReactNode{const content=tree[JSON.stringify(segments)];return <>{content?.files.map(file=>fileRow(file,segments,'tree'))}{content?.folders.map(folder=>{const next=[...segments,folder.name],key=JSON.stringify(next),opened=expanded.includes(key);return <div className="folderTreeBranch" key={key}><div className="folderTreeDirectory"><button className="directoryToggle" disabled={busy} onClick={()=>opened?setExpanded(current=>current.filter(value=>value!==key)):void open(device,next)}>{opened?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><FolderClosed size={15}/><button className="directoryDestinationName" disabled={busy} onClick={()=>opened?setExpanded(current=>current.filter(value=>value!==key)):void open(device,next)}>{folder.name}</button></div>{opened&&<div className="folderTreeChildren">{renderTree(next)}</div>}</div>})}</>}
 const chosen=selected.map(key=>ready[key]).filter(Boolean);
 return <section className="sourceCard phoneSourceCard"><div className="sourceHeader phoneCompactHeader"><Smartphone size={19}/><span className="sourceTitle">Phone</span><button className="usbRefresh" title="Refresh phone" disabled={busy||recentBusy} onClick={()=>void refresh()}><RefreshCw className={busy||recentBusy?'spin':''} size={14}/></button><label className="phoneHours"><input type="number" min="0.1" step="any" defaultValue={hours} key={hours} aria-label="Recent phone file hours" onBlur={event=>{const value=event.currentTarget.valueAsNumber;if(Number.isFinite(value)&&value>0)onHoursChange?.(value);else event.currentTarget.value=String(hours);}}/>h</label><span className="phoneHeaderSearch"><Search size={12}/><input type="search" placeholder="Search…" value={query} onChange={event=>setQuery(event.target.value)}/></span><select aria-label="Connected phone" value={device} onChange={event=>select(event.target.value)} disabled={busy}><option value="">Choose phone</option>{devices.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><label className="phoneTypes">Recent files <select value={category} onChange={event=>setCategory(event.target.value as 'all'|'image'|'file')}><option value="all">All ({counts.image+counts.file})</option><option value="image">Images ({counts.image})</option><option value="file">Files ({counts.file})</option></select></label>{!!selected.length&&<div className="emailToolbar recentSelectionToolbar"><button onClick={()=>setSelected([])}>Deselect all</button><button onClick={()=>void Promise.all(chosen.map(file=>fetch(`${API_BASE_URL}/search-files/open`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file.path})})))}>Open files</button><button className="recentBatchFire" onClick={()=>window.dispatchEvent(new CustomEvent('folderrocket-add-to-fire',{detail:chosen}))}><Flame size={12}/>Fire Mountain</button></div>}<div className="usbFileList folderTreeRoot">{recentVisible.map(file=>fileRow(file,file.segments||[],'recent'))}{recentBusy&&<p>Scanning recent phone files…</p>}{truncated&&!recentBusy&&<p>Partial result: use fewer hours or Images/Files to shorten the scan.</p>}{!recentBusy&&device&&!recentVisible.length&&<p>No matching recent files.</p>}<details className="phoneBrowseTree"><summary>Browse phone folders</summary>{renderTree([])}</details>{!devices.length&&!busy&&<p>Connect and unlock your phone, then choose Trust this computer.</p>}</div>{error&&<small className="usbError" role="alert">{error}</small>}</section>;
}
