import {useEffect,useMemo,useRef,useState} from 'react';
import {Clock,ExternalLink,Flame,RefreshCw} from 'lucide-react';
import {UsbFileIcon} from './UsbSourcePanel';
import {API_BASE_URL} from '../api';
import {SEARCH_RESULT_TYPE} from './SearchWorkspace';
import {recentFileCategory,recentFileCategoryLabel,type RecentFileCategory} from '../recentFileTypes';
interface RecentFile{name:string;path:string;size:number;createdAt:string;downloaded:boolean;}
interface Props{folders:string[];extraPaths?:string;hours?:number;onSettings:(hours:number,paths:string)=>void;}
export default function RecentFilesSourcePanel({folders,hours=24,onSettings}:Props){
 const[files,setFiles]=useState<RecentFile[]>([]),[selected,setSelected]=useState<string[]>([]);
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState<'all'|RecentFileCategory>('all');const request=useRef(0);
 const counts=useMemo(()=>files.reduce<Record<RecentFileCategory,number>>((all,file)=>{all[recentFileCategory(file.name)]++;return all;},{pdf:0,word:0,text:0,excel:0,powerpoint:0,other:0}),[files]);
 const visible=useMemo(()=>files.filter(file=>(category==='all'||recentFileCategory(file.name)===category)&&`${file.name} ${file.path}`.toLowerCase().includes(query.toLowerCase())),[files,query,category]);const chosen=files.filter(file=>selected.includes(file.path));
 function saveHours(input:HTMLInputElement){const value=input.valueAsNumber;if(Number.isFinite(value)&&value>0){if(value!==hours)onSettings(value,'');}else input.value=String(hours);}
 async function openFiles(items:RecentFile[]){const results=await Promise.all(items.map(file=>fetch(`${API_BASE_URL}/search-files/open`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file.path})})));if(results.some(response=>!response.ok))setMessage('One or more files could not be opened.');}
 function sendToFire(items:RecentFile[]){if(!items.length)return;window.dispatchEvent(new CustomEvent('folderrocket-add-to-fire',{detail:items}));setMessage(`${items.length} file${items.length===1?'':'s'} added to Fire Mountain.`);}
 function drag(event:React.DragEvent<HTMLElement>,file:RecentFile){const items=selected.includes(file.path)?chosen:[file];const value=JSON.stringify(items);event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-folderrocket-daily-source','recent');event.dataTransfer.setData(SEARCH_RESULT_TYPE,value);event.dataTransfer.setData('text/plain',`folderrocket-search:${value}`);}
 async function refresh(){const id=++request.current;setBusy(true);setMessage('');try{const response=await fetch(`${API_BASE_URL}/files/recent`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({hours,folders})});const data=await response.json();if(id!==request.current)return;if(!response.ok)throw new Error(data.message||'Unable to read recent files.');setFiles(data.files||[]);setSelected(current=>current.filter(path=>(data.files||[]).some((file:RecentFile)=>file.path===path)));setMessage(data.truncated?'Partial scan: narrow the period and refresh.':`${data.files.length} recent files.`);}catch(error){if(id===request.current)setMessage(error instanceof Error?error.message:'Scan failed.');}finally{if(id===request.current)setBusy(false);}}
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void refresh();});return()=>{active=false;request.current++;};},[hours]); // eslint-disable-line react-hooks/exhaustive-deps
 return <section className="sourceCard recentSourceCard"><div className="sourceHeader recentCompactHeader"><Clock size={19}/><span className="sourceTitle">Recent files</span><button className="usbRefresh" title="Refresh recent files" disabled={busy} onClick={()=>void refresh()}><RefreshCw className={busy?'spin':''} size={14}/></button><label className="recentHours"><input key={hours} type="number" min="0.1" step="any" aria-label="Recent file hours" defaultValue={hours} onBlur={event=>saveHours(event.currentTarget)} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}}/>h</label><input className="recentHeaderSearch" type="search" placeholder="Search…" aria-label="Find recent files" value={query} onChange={event=>setQuery(event.target.value)}/></div><label className="recentTypeFilter"><span>Filter</span><select value={category} onChange={event=>setCategory(event.target.value as 'all'|RecentFileCategory)}><option value="all">All ({files.length})</option>{(Object.keys(counts) as RecentFileCategory[]).filter(kind=>counts[kind]>0).map(kind=><option value={kind} key={kind}>{recentFileCategoryLabel[kind]} ({counts[kind]})</option>)}</select></label>{!!files.length&&<div className="emailToolbar recentSelectionToolbar"><button disabled={!selected.length} onClick={()=>setSelected([])}>Deselect all</button><button disabled={!selected.length} onClick={()=>void openFiles(chosen)}>Open files</button></div>}<div className="usbFileList">{visible.map(file=><div className={selected.includes(file.path)?'inspectorFile usbInspectorFile selectedAttachment':'inspectorFile usbInspectorFile'} key={file.path} draggable onClick={()=>setSelected(current=>current.includes(file.path)?current.filter(path=>path!==file.path):[...current,file.path])} onDragStart={event=>drag(event,file)} title={`${file.path} · ${new Date(file.createdAt).toLocaleString()}`}><button type="button" className="recentFileFire" title={selected.includes(file.path)&&chosen.length>1?`Add ${chosen.length} selected files to Fire Mountain`:`Add ${file.name} to Fire Mountain`} onClick={event=>{event.stopPropagation();sendToFire(selected.includes(file.path)?chosen:[file]);}}><Flame size={14}/></button><span className="inspectorFileName"><UsbFileIcon name={file.name}/><strong>{file.name}</strong></span><small>{file.size>=1048576?`${(file.size/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(file.size/1024))} KB`}</small><button type="button" className="recentFileOpen" title={`Open ${file.name}`} onClick={event=>{event.stopPropagation();void openFiles([file]);}}><ExternalLink size={14}/></button></div>)}</div><small className="usbNote" role="status">{busy?'Scanning recent files…':message}</small></section>;
}
